### ISSUE TITLE
New version for Scala 2.13

### ISSUE THREAD

**Issue by csaltos** [ancane/hashids.scala#2]
Hi @ancane !! ... thank you very much for your code ... may you help us with a new version for Scala 2.13 ? ... if you like we can help with a new PR for that.

Best regards,

Carlos Saltos

**Comment by ancane** [comment]
Thank you, @csaltos. Didn't expect it was used by anyone, TBH. Published 2.13 last night. Please, try and tell if it that was ok. https://search.maven.org/artifact/com.github.ancane/hashids-scala_2.13/1.4/jar
